# -
#     type: dino
#     args:
#         dino_type: dinov2_vitb14
#         dino_layers: [10]
#         image_insize: [686, 364]
#         desc_facet: value
# - 
#     type: vlad
#     args:
#         n_clusters: 8
#         cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_364x686_

# -
#     type: loftup
#     args:
#         image_insize: [224, 224]
# - 
#     type: vlad
#     args:
#         n_clusters: 8
#         cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_loftup_dinov2s_224x224

-
    type: jafar
    args:
        image_insize: [224, 224]
- 
    type: vlad
    args:
        n_clusters: 16
        cache_dir: physics_atv_visual_mapping/dino_clusters/16_clusters_jafar_dinov2s_224x224
        # n_clusters: 16
        # cache_dir: physics_atv_visual_mapping/dino_clusters/16_clusters_jafar_dinov2b_224x224

# -
#     type: radio_lang
#     args:
#         image_insize: [848, 448]
#         radio_type: c-radio_v3-b
#         adaptor_type: siglip2

# - 
#     type: pca
#     args:
#         fp: physics_atv_visual_mapping/pca/radio_v3b_siglip2.pt