-
    type: loftup
    args:
        image_insize: [224, 224]
        featurizer: anythermal 
        upsampler: loftup_dinov2b
# - 
    # type: vlad
    # args:
    #     n_clusters: 8
    #     cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_loftup_dinov2s_thermal_224x224

