# - 
#     type: vlad
#     args:
#         n_clusters: 8
#         cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_loftup_dinov2s_224x224
- 
    type: vlad
    args:
        n_clusters: 16
        cache_dir: physics_atv_visual_mapping/dino_clusters/16_clusters_radio

