models_dir: /home/tartandriver/tartandriver_ws/models #necessary to include this for non-ROS offline proc

image_processing: !include /home/tartandriver/tartandriver_ws/src/perception/physics_atv_visual_mapping/config/image_processing/loftup_vlad.yaml
            
localmapping: !include /home/tartandriver/tartandriver_ws/src/perception/physics_atv_visual_mapping/config/localmapping/cov_voxel.yaml

terrain_estimation: !include /home/tartandriver/tartandriver_ws/src/perception/physics_atv_visual_mapping/config/terrain_estimation/voxel_to_bev.yaml

device: cuda
viz: True
