-
    type: anythermal
    args:
        input_size: [224, 224]

- 
    type: vlad
    args:
        n_clusters: 8
        cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_anythermal_16x16