-
    type: bilinear
    args:
        image_insize: [224,224]
        featurizer: anythermal

- 
    type: vlad
    args:
        n_clusters: 8
        cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_bilinear_anythermal_224x224