-
    type: bilinear
    args:
        image_insize: [224,224]
        featurizer: dinov2b
        grayscale: False
- 
    type: pca
    args:
        fp: physics_atv_visual_mapping/pca/pca_bilinear_dinov2b_thermal_224x224.pt