-
    type: bilinear
    args:
        image_insize: [224,224]
        featurizer: dinov2b
        grayscale: False
- 
    type: vlad
    args:
        n_clusters: 8
        cache_dir: physics_atv_visual_mapping/dino_clusters/8_clusters_bilinear_dinov2b_thermal_224x224