-
    type: dinov2_featurizer
    args:
        model_type: dinov2b
        input_size: [224,224]
        grayscale: False
- 
    type: pca
    args:
        fp: physics_atv_visual_mapping/pca/pca_dinov2b_thermal_16x16.pt